version: '3'
services:
  redis:
    image: "redis:alpine"
    expose:
    - "6379"
    ports:
    - "6379:6379"
  geth-lb:
    command: ["go", "run", "/go/src/geth-lb/server/server.go"]
    build:
      context: .
    ports:
    - "8545:8545"
    volumes:
    - ./:/go/src/geth-lb
    links:
    - redis