version: '3'
services:
  redis:
    image: "redis:alpine"
    expose:
    - "6379"
    ports:
    - "6379:6379"
  geth-lb:
    command: ["go", "run", "/go/src/geth-lb/server/server.go"]
    build:
      context: .
    ports:
    - "8545:8545"
    environment:
      LISTEN_PORT: "8545"
      BACKEND_URL: "https://rpc-staging.public.test.k8s.2key.net"
      REDIS_ADDRESS: "redis:6379"
      REDIS_PASSWORD: ""
      REDIS_DATABASE: "0"
    volumes:
    - ./:/go/src/geth-lb
    links:
    - redis